In [1]:
import pandas as pd
        
creditcard = pd.read_csv('https://drive.google.com/open?id=1sPYbGjfxoXS9G2Y4JcjD-N5K7KFnHAkU&usp=drive_copy')
creditcard

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [3]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
pd.options.display.max_columns = None

In [5]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0

In [6]:
data.tail()

Time         V1         V2        V3        V4        V5  \
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9       V10       V11       V12  \
284802 -2.606837 -4.918215  7.305334  1.914428  4.356170 -1.593105  2.711941   
284803  1.058415  0.024330  0.294869  0.584800 -0.975926 -0.150189  0.915802   
284804  3.031260 -0.296827  0.708417  0.432454 -0.484782  0.411614  0.063119   
284805  0.623708 -0.686180  0.679145  0.392087 -0.399126 -1.933849 -0.962886   
284806 -0.649617  1.577006 -0.414650  0.486180 -0.915427 -1.040458 -0.031513   

             V13       V14       V15       V16       V17       V18       V19  \
284802 -0.689256  4.626942 -0.924459  1.107641  1.991691  0.510632 -0.682920   
284803  1.214756 -0.675143  1.164931 -0.711757 -0.025693 -1.221179 -1.545556   
284804 -0.183699 -0.510602  1.329284  0.140716  0.313502  0.395652 -0.577252   
284805 -1.042082  0.449624  1.962563 -0.608577  0.509928  1.113981  2.897849   
284806 -0.188093 -0.084316  0.041333 -0.302620 -0.660377  0.167430 -0.256117   

             V20       V21       V22       V23       V24       V25       V26  \
284802  1.475829  0.213454  0.111864  1.014480 -0.509348  1.436807  0.250034   
284803  0.059616  0.214205  0.924384  0.012463 -1.016226 -0.606624 -0.395255   
284804  0.001396  0.232045  0.578229 -0.037501  0.640134  0.265745 -0.087371   
284805  0.127434  0.265245  0.800049 -0.163298  0.123205 -0.569159  0.546668   
284806  0.382948  0.261057  0.643078  0.376777  0.008797 -0.473649 -0.818267   

             V27       V28  Amount  Class  
284802  0.943651  0.823731    0.77      0  
284803  0.068472 -0.053527   24.79      0  
284804  0.004455 -0.026561   67.88      0  
284805  0.108821  0.104533   10.00      0  
284806 -0.002415  0.013649  217.00      0

In [7]:
data.shape

(284807, 31)

In [8]:
print("Number of columns: {}".format(data.shape[1]))
print("Number of rows: {}".format(data.shape[0]))

Number of columns: 31
Number of rows: 284807


In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [10]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [11]:
# Normalize the Amount attribute

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc = StandardScaler()
data['Amount'] = sc.fit_transform(pd.DataFrame(data['Amount']))

In [14]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

     Amount  Class  
0  0.244964      0  
1 -0.342475      0  
2  1.160686      0  
3  0.140534      0  
4 -0.073403      0

In [15]:
data = data.drop(['Time'], axis =1)

In [16]:
data.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

     Amount  Class  
0  0.244964      0  
1 -0.342475      0  
2  1.160686      0  
3  0.140534      0  
4 -0.073403      0

In [17]:
# Checking duplicates and Remove duplicates

In [18]:
data.duplicated().any()

True

In [19]:
data = data.drop_duplicates()

In [20]:
data.duplicated().any()

False

In [21]:
data.shape

(275663, 30)

In [22]:
data['Class'].unique()

array([0, 1], dtype=int64)

In [23]:
data['Class'].value_counts()

Class
0    275190
1       473
Name: count, dtype: int64

In [ ]:
# Split the data into training and testing data

In [23]:
X = data.drop('Class', axis = 1)
y=data['Class']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [27]:
import numpy as np

In [28]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [29]:
classifier = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Random Forest Classifier": RandomForestClassifier(),
    "Support Vector Classifier": SVC(),
    "K-Nearest Neighbors Classifier": KNeighborsClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "Bagging Classifier": BaggingClassifier(),
    "Extra Trees Classifier": ExtraTreesClassifier(),
    "Stochastic Gradient Descent Classifier": SGDClassifier(),
    "Voting Classifier": VotingClassifier(estimators=[
        ('lr', LogisticRegression()),
        ('dt', DecisionTreeClassifier()),
        ('rf', RandomForestClassifier()),
        ('svc', SVC()),
        ('knn', KNeighborsClassifier())
    ], voting='hard')
}

for name, clf in classifier.items():
    print(f"\n=========={name}===========")
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    # Evaluation Metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    print(f"\n Accuracy: {accuracy}")
    print(f" Precision: {precision}")
    print(f" Recall: {recall}")
    print(f" F1 Score: {f1}")
    
    # Confusion Matrix
    print("\n Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    
    # Classification Report
    print("\n Classification Report:")
    print(classification_report(y_test, y_pred))


==========Logistic Regression===========

 Accuracy: 0.9992563437505668
 Precision: 0.890625
 Recall: 0.6263736263736264
 F1 Score: 0.7354838709677419

 Confusion Matrix:
[[55035     7]
 [   34    57]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.89      0.63      0.74        91

    accuracy                           1.00     55133
   macro avg       0.95      0.81      0.87     55133
weighted avg       1.00      1.00      1.00     55133


==========Decision Tree Classifier===========

 Accuracy: 0.9989661364337148
 Precision: 0.6574074074074074
 Recall: 0.7802197802197802
 F1 Score: 0.7135678391959799

 Confusion Matrix:
[[55005    37]
 [   20    71]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.66      0.78      0.71        91

    accuracy                          

C:\Users\Hammad\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(



 Accuracy: 0.9991112400921408
 Precision: 0.75
 Recall: 0.6923076923076923
 F1 Score: 0.72

 Confusion Matrix:
[[55021    21]
 [   28    63]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.75      0.69      0.72        91

    accuracy                           1.00     55133
   macro avg       0.87      0.85      0.86     55133
weighted avg       1.00      1.00      1.00     55133


==========Gradient Boosting Classifier===========

 Accuracy: 0.9986033772876499
 Precision: 0.71875
 Recall: 0.25274725274725274
 F1 Score: 0.37398373983739835

 Confusion Matrix:
[[55033     9]
 [   68    23]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.72      0.25      0.37        91

    accuracy                           1.00     55133
   macro avg       0.86      0.63      0.69     5

In [31]:
# Undersampling

In [32]:
normal = data[data['Class']==0]
fraud = data[data['Class']==1]

In [33]:
normal.shape

(275190, 30)

In [34]:
fraud.shape

(473, 30)

In [35]:
normal_sample = normal.sample(n=473)

In [36]:
normal_sample.shape

(473, 30)

In [37]:
new_data = pd.concat([normal_sample,fraud], ignore_index=True)

In [38]:
new_data.head()

V1        V2        V3        V4        V5        V6        V7  \
0  1.793689 -1.239021 -1.376742 -0.602319 -0.814262 -0.512090 -0.746769   
1  1.141245  0.093624  0.415084  1.291345 -0.550529 -0.858319  0.043902   
2  1.972674 -0.093187 -1.233452  0.295309  0.208456  0.016800 -0.465885   
3  1.957147  0.037269 -1.834236  0.570097  0.155513 -1.410113  0.300801   
4  1.908669 -0.135349  0.342800  1.586544 -0.743453 -0.177588 -0.824323   

         V8        V9       V10       V11       V12       V13       V14  \
0 -0.062523 -0.225644  0.166345  1.057078 -0.060494  0.432334 -1.943658   
1 -0.108633  0.231944  0.077884 -0.652070 -0.572349 -1.361366  0.593707   
2  0.140538  0.547152 -0.232538  0.826180  0.418672  0.015936 -0.934378   
3 -0.355341  0.648768 -0.532808 -0.402591 -0.182751 -0.416366 -0.735453   
4 -0.013461  2.437398 -0.239894  0.036797 -2.012993  1.979577  1.177955   

        V15       V16       V17       V18       V19       V20       V21  \
0 -0.347649  1.983604  0.975431  0.173327  0.581008  0.416249  0.371446   
1  1.137373  0.274576 -0.409410  0.106954 -0.478363 -0.139826  0.044723   
2  0.602405  1.455869 -0.283045  1.029563  0.029239 -0.072298 -0.237598   
3  1.013577  0.224085  0.533059  0.541158 -0.506201 -0.134372  0.216121   
4 -0.069397  0.470450  0.006486  0.425218 -0.950316 -0.271502 -0.083230   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.757648 -0.109526 -0.489145 -0.182441 -0.102207 -0.005853  0.004785   
1  0.000156 -0.096358  0.357198  0.545569 -0.329427  0.004354  0.029195   
2 -0.763868  0.342056 -0.052586 -0.554429 -0.071680 -0.020986 -0.017720   
3  0.676050 -0.062358 -0.165467  0.215245 -0.097744 -0.010106 -0.022452   
4  0.182622  0.287491 -0.112795 -0.373025 -0.789292  0.055214 -0.025261   

     Amount  Class  
0  0.402409      0  
1 -0.157323      0  
2 -0.253357      0  
3 -0.142570      0  
4 -0.301854      0

In [39]:
new_data['Class'].value_counts()

Class
0    473
1    473
Name: count, dtype: int64

In [40]:
X = new_data.drop('Class', axis = 1)
y= new_data['Class']

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [42]:
classifier = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree Classifier": DecisionTreeClassifier()
}

for name, clf in classifier.items():
    print(f"\n=========={name}===========")
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(f"\n Accuaracy: {accuracy_score(y_test, y_pred)}")
    print(f"\n Precision: {precision_score(y_test, y_pred)}")
    print(f"\n Recall: {recall_score(y_test, y_pred)}")
    print(f"\n F1 Score: {f1_score(y_test, y_pred)}")


==========Logistic Regression===========

 Accuaracy: 0.9421052631578948

 Precision: 0.9789473684210527

 Recall: 0.9117647058823529

 F1 Score: 0.9441624365482234

==========Decision Tree Classifier===========

 Accuaracy: 0.8894736842105263

 Precision: 0.900990099009901

 Recall: 0.8921568627450981

 F1 Score: 0.896551724137931


In [43]:
# OVERSAMPLING

In [44]:
X = data.drop('Class', axis = 1)
y= data['Class']

In [45]:
X.shape

(275663, 29)

In [46]:
y.shape

(275663,)

In [48]:
!pip install imbalanced-learn


   ---------------------------------------- 0.0/258.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/258.0 kB ? eta -:--:--
   - -------------------------------------- 10.2/258.0 kB ? eta -:--:--
   - -------------------------------------- 10.2/258.0 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/258.0 kB 163.8 kB/s eta 0:00:02
   ------ -------------------------------- 41.0/258.0 kB 163.4 kB/s eta 0:00:02
   ------ -------------------------------- 41.0/258.0 kB 163.4 kB/s eta 0:00:02
   ------------- ------------------------- 92.2/258.0 kB 308.0 kB/s eta 0:00:01
   --------------------- ---------------- 143.4/258.0 kB 405.9 kB/s eta 0:00:01
   ---------------------------- --------- 194.6/258.0 kB 491.5 kB/s eta 0:00:01
   --------------------------------- ---- 225.3/258.0 kB 550.0 kB/s eta 0:00:01
   -------------------------------------  256.0/258.0 kB 542.5 kB/s eta 0:00:01
   -------------------------------------- 258.0/258.0 kB 511.9 kB/s eta 0:

In [49]:
from imblearn.over_sampling import SMOTE

In [50]:
X_res, y_res = SMOTE().fit_resample(X,y)

In [51]:
y_res.value_counts()

Class
0    275190
1    275190
Name: count, dtype: int64

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size = 0.2, random_state = 42)

In [53]:
classifier = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree Classifier": DecisionTreeClassifier()
}

for name, clf in classifier.items():
    print(f"\n=========={name}===========")
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(f"\n Accuaracy: {accuracy_score(y_test, y_pred)}")
    print(f"\n Precision: {precision_score(y_test, y_pred)}")
    print(f"\n Recall: {recall_score(y_test, y_pred)}")
    print(f"\n F1 Score: {f1_score(y_test, y_pred)}")


==========Logistic Regression===========

 Accuaracy: 0.944819942585123

 Precision: 0.9728810283173867

 Recall: 0.915077359416759

 F1 Score: 0.9430943056830744

==========Decision Tree Classifier===========

 Accuaracy: 0.9981376503506668

 Precision: 0.9975123474723998

 Recall: 0.9987637037979746

 F1 Score: 0.9981376334317511


In [54]:
# Reduce the Number of Columns

In [55]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
data_standardized = pd.concat([X_res, y_res], axis=1)
data_pca = pca.fit_transform(data_standardized)
explained_variance_ratio = pca.explained_variance_ratio_
print("Explained Variance Ratio:", explained_variance_ratio)

Explained Variance Ratio: [0.71930027 0.09202689 0.05825089 0.041346   0.01201694 0.00950605
 0.00848523 0.00725797 0.00607673 0.00491948]


In [73]:
x=data_pca
y=y_res
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [74]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [75]:
y_pred = dtc.predict(X_test)
print(f"\n Accuaracy: {accuracy_score(y_test, y_pred)}")
print(f"\n Precision: {precision_score(y_test, y_pred)}")
print(f"\n Recall: {recall_score(y_test, y_pred)}")
print(f"\n F1 Score: {f1_score(y_test, y_pred)}")


 Accuaracy: 0.9974563029179839

 Precision: 0.9966781027065295

 Recall: 0.9982364598294639

 F1 Score: 0.9974566726010973


In [76]:
import joblib

In [77]:
joblib.dump(dtc, "credit_card_model.pkl")

['credit_card_model.pkl']

In [78]:
model = joblib.load("credit_card_model.pkl")

In [148]:
pred = model.predict([[-1.3598071336738,0.0727811733098497,1.53634673796914,1.37815522427443,-1.338320769942518,-1.462387777762292,0.239598554061257,1.0986979012610507,0.363786969611213,-0.0907941719789316]])

In [149]:
pred

array([0], dtype=int64)

In [88]:
if pred[0] == 0:
    print("Normal Transcation")
else:
    print("Fraud Transcation")

Fraud Transcation


In [30]:
import tkinter as tk
from tkinter import messagebox
import numpy as np
import joblib

# Load your trained model
model = joblib.load('credit_card_model.pkl')

def predict():
    # Get values from entry fields
    values = [float(entry.get()) for entry in entries]
    
    # Perform prediction
    prediction = model.predict([values])[0]
    if prediction == 0:
        result = "normal transaction"
    else:
        result = "fraud transaction"
    messagebox.showinfo("Prediction Result", f"The prediction is: {result}")

# Create tkinter window
window = tk.Tk()
window.title("Credit Card Fraud Detection System")
window.geometry("500x400")

# Set dark theme colors
bg_color = "#2c3e50"  # Background color
fg_color = "#ecf0f1"  # Foreground color
btn_bg_color = "#3498db"  # Button background color
btn_fg_color = fg_color  # Button foreground color

# Set background color for window
window.configure(bg=bg_color)

# Custom font
custom_font = ("Helvetica", 12, "bold")

# Title label
title_label = tk.Label(window, text="Credit Card Fraud Detection System", font=("Helvetica", 16, "bold"), bg=bg_color, fg=fg_color)
title_label.grid(row=0, column=0, columnspan=2, pady=10)

# Default values for each feature
default_values = [-1.3598071336738, 0.0727811733098497, 1.53634673796914, 1.37815522427443, -1.338320769942518, -1.462387777762292, 0.239598554061257, 1.0986979012610507, 0.363786969611213, -0.0907941719789316]

# Create entry fields for each feature with default values
feature_names = ['Feature1', 'Feature2', 'Feature3', 'Feature4', 'Feature5', 'Feature6', 'Feature7', 'Feature8', 'Feature9', 'Feature10']
entries = []
for i, (feature_name, default_value) in enumerate(zip(feature_names, default_values), start=1):
    label = tk.Label(window, text=feature_name, font=custom_font, bg=bg_color, fg=fg_color)
    label.grid(row=i, column=0, pady=5, padx=5, sticky="w")
    default_var = tk.StringVar(value=default_value)
    entry = tk.Entry(window, textvariable=default_var, font=custom_font, bg=fg_color, fg=bg_color)
    entry.grid(row=i, column=1, pady=5, padx=5)
    entries.append(entry)

# Create predict button
predict_button = tk.Button(window, text="Predict", command=predict, font=custom_font, bg=btn_bg_color, fg=btn_fg_color)
predict_button.grid(row=len(feature_names)+1, column=0, columnspan=2, pady=10)

# Add some color and interactivity to the window
window.option_add("*TButton.Background", btn_bg_color)
window.option_add("*TButton.Foreground", btn_fg_color)
window.option_add("*Font", custom_font)

# Run tkinter event loop
window.mainloop()
